#!/usr/bin/python3


from tkinter import *
from tkinter import ttk
from sys import exit, stdout
import json


NoModuleString = "No module found"


def Choose(*args):
    try:
        items = map( int, modlist.curselection() )
        for index in items:
            rsrc = modlist.get( index )
            if rsrc!=NoModuleString:
                stdout.write( "%s\n"%( rsrc ) )
        stdout.flush()
        root.destroy()
    except TclError:
        pass
    except ValueError:
        pass
    

from argparse import ArgumentParser
parser = ArgumentParser( "Chooser" )
parser.add_argument( "--multiple", "-m", action='store_true', default=None )
parser.add_argument( "inputs", type=str, nargs="*" )

args = parser.parse_args()

if len( args.inputs )>0:
    if args.multiple:
        for i in args.inputs:
            stdout.write( "%s\n"%( i ) )
    else:
        stdout.write( "%s\n"%( args.inputs[0] ) )
    stdout.flush()
    exit( 0 )

root = Tk()
root.title("Choose Module")

mainframe = ttk.Frame( root, padding="3 3 12 12" )
#mainframe.grid( column=0, row=0, sticky=( N, W, E, S ) )
mainframe.pack( side="top", fill="both", expand=True )
mainframe.columnconfigure( 0, weight=1 )
mainframe.rowconfigure( 0, weight=1 )

ttk.Label( mainframe, text="Modules" ).pack( side="top", fill="x", expand=False)

modules = []

try:
    from AgVisa import *
    ModelsList = {
        "U5303A": ( 0x15bc, 0x1296 ),
        "U5309A": ( 0x15bc, 0x12c4 ),
        "M9709A": ( 0x15bc, 0x12c6 ),
        "M9703B": ( 0x15bc, 0x1301 ),
    }

    modules = []
    rm = viOpenDefaultRM()
    try:
        fl, nbr, desc = viFindRsrc( rm, "PXI?*::INSTR" )
        try:
            for n in range( nbr ):
                if n!=0:
                    desc = viFindNext( fl )
                s = viOpen( rm, desc, VI_NULL, VI_NULL )
                try:
                    manfId =  viGetAttributeUInt16( s, VI_ATTR_MANF_ID )
                    modelId = viGetAttributeUInt16( s, VI_ATTR_MODEL_CODE )

                    if ( manfId, modelId ) in ModelsList.values():
                        modules.append( desc )

                finally:
                    viClose( s )
        finally:
            viClose( fl )
    except RuntimeError:
        # Usually generated by VISA error no such resource. Ignore.
        pass
    finally:
        viClose( rm )
except:
    pass

if len( modules )==0:
    modules.append( NoModuleString )
selectmode = "single"
if args.multiple:
    selectmode = "multiple"
modlist = Listbox( mainframe, selectmode=selectmode )
for item in modules:
    modlist.insert( END, item )
modlist.activate( 0 )
modlist.bind( "<Double-Button-1>", Choose )
modlist.pack( side="top", fill="both", expand=True )

ttk.Button( mainframe, text="Choose", command=Choose ).pack( side="bottom", fill="x", expand=False )

modlist.focus()
root.bind('<Return>', Choose)

root.mainloop()

